# Generated by Django 4.1 on 2022-08-19 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='create',
            old_name='headline',
            new_name='title',
        ),
    ]
